import Head from 'next/head'
import styles from '../styles/Home.module.css'
import "bootstrap/dist/css/bootstrap.min.css"
import { useState } from 'react'
import { useRouter } from "next/router"

export default function Home() {

  const [inputValues, setInputValues] = useState({})

  const handleClick = () => {
    var query = `mutation newProduct($input: ProductInput) {
      newProduct(input: $input) {
        name
        productionCapacity
        price
        description
      }
    }`;

    fetch('http://localhost:3000/api/graphql', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Accept': 'application/json',
      },
      body: JSON.stringify({
        query,
        variables: {
          input: {
            ...inputValues
          }
        }
      })
    })
      .then(r => r.json())
      .then(data => console.log('data returned:', data));
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container h-100">
        <div className="row h-100 justify-content-center align-items-center">
          <div className="col-10 col-md-8 col-lg-6">
            <h1>Product Details</h1>
            <div className="py-3">
              <h5>Product Name</h5>
              <input type="text" id="name" label="Mobile Name" variant="standard" onChange={(e) => setInputValues({ ...inputValues, [e.target.id]: e.target.value })} />
            </div>
            <div className="py-3">
              <h5>Production Capacity</h5>
              <input type="text" id="productionCapacity" label="Description" variant="standard" onChange={(e) => setInputValues({ ...inputValues, [e.target.id]: Number(e.target.value) })} />
            </div>
            <div className="py-3">
              <h5>Price</h5>
              <input type="text" id="price" label="Description" variant="standard" onChange={(e) => setInputValues({ ...inputValues, [e.target.id]: Number(e.target.value) })} />
            </div>
            <div className="py-3">
              <h5>Description</h5>
              <input type="text" id="description" label="Description" variant="standard" onChange={(e) => setInputValues({ ...inputValues, [e.target.id]: e.target.value })} />
            </div>
            <div>
              <button className="btn btn-success" onClick={handleClick}>Submit</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
