import Head from 'next/head'
import styles from '../styles/Home.module.css'
import "bootstrap/dist/css/bootstrap.min.css"
import axios from "axios"
import { useEffect, useState } from 'react';
import Link from 'next/link'

export default function ProductLsit() {

    const [data, setData] = useState({})

    useEffect(() => {
        const options = {
            method: 'POST',
            url: 'http://localhost:3000/api/graphql',
            headers: {
                'content-type': 'application/json'
            },
            data: {
                query: `{
                getProducts {
                            name
                            id
                            productionCapacity
                            description
                        }
                    }`
            }
        };
        axios
            .request(options)
            .then(function (response) {
                console.log(response.data); // Response
                setData(response.data)

            })
            .catch(function (error) {
                console.error(error);
            });
    }, [])

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <table className='table table-bordered ' style={{ width: "75%" }}  >
                <thead class="thead-dark">
                    <tr>
                        <th>Name </th>
                        <th>Capacity</th>
                        <th>Decscription</th>
                    </tr>
                </thead>
                {data?.data?.getProducts.map((val) => {
                    return (
                        <>
                            <tr className="my-3">
                                <td>{val.name}</td>
                                <td>{val.productionCapacity}</td>
                                <td>{val.description}</td>
                            </tr>
                        </>
                    )
                })}
            </table>

            <Link href="/">
                <button className="btn btn-success" >submit</button>
            </Link>

        </div>
    )
}
